name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Clean project
        run: ./flightReservationSystem/gradlew clean

      - name: Run all tests
        run: ./flightReservationSystem/gradlew testClasses
